// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJFVdNab2_Ot-gqE-af0CGatqSANVLMc',
    appId: '1:762625957989:web:56bfd0b996f949eee6268c',
    messagingSenderId: '762625957989',
    projectId: 'apps-863e1',
    authDomain: 'apps-863e1.firebaseapp.com',
    storageBucket: 'apps-863e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbyDIWdSlW-o9uZHtUNqq9n9uGYm618ac',
    appId: '1:762625957989:android:259d8b2f1c3bc636e6268c',
    messagingSenderId: '762625957989',
    projectId: 'apps-863e1',
    storageBucket: 'apps-863e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdFmYG0FJerhc_ajB3VIiyzcAuf7k7FF8',
    appId: '1:762625957989:ios:9b42e5a576aef0ace6268c',
    messagingSenderId: '762625957989',
    projectId: 'apps-863e1',
    storageBucket: 'apps-863e1.firebasestorage.app',
    iosBundleId: 'com.example.apps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdFmYG0FJerhc_ajB3VIiyzcAuf7k7FF8',
    appId: '1:762625957989:ios:9b42e5a576aef0ace6268c',
    messagingSenderId: '762625957989',
    projectId: 'apps-863e1',
    storageBucket: 'apps-863e1.firebasestorage.app',
    iosBundleId: 'com.example.apps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmJFVdNab2_Ot-gqE-af0CGatqSANVLMc',
    appId: '1:762625957989:web:58a10ad47b6cb249e6268c',
    messagingSenderId: '762625957989',
    projectId: 'apps-863e1',
    authDomain: 'apps-863e1.firebaseapp.com',
    storageBucket: 'apps-863e1.firebasestorage.app',
  );
}
